name: Build an ISO

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

env:
    TOKEN: ${{ secrets.CONSTELLATION_TOKEN }}
    HOST: ${{ secrets.CONSTELLATION_HOST }}

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
            options: --privileged
        steps:
            - uses: actions/checkout@v2
            - name: Prepare keyring
              run: |
                  pacman-key --init
                  pacman --noconfirm -Sy archlinux-keyring
            
            - name: Install tools
              run: |
                  rm /etc/pacman.conf
                  cp pacman.conf /etc/pacman.conf
                  pacman --noconfirm -Syyu
                  pacman --noconfirm -S archiso git mkodyseniso jq
            
            - name: Build ISO
              run: |
                  mkodyseniso -v .

            - name: Upload ISO
              run: |
                  echo "Uploading to Constellation..."
                  ls out
                  sleep 4
                  curl -H "Content-Type: multipart/form-data" -H "authorization: ${{ env.TOKEN }}" -H "Format: NAME" -H "Override-Domain: files.odysen.space" -F "file=@$(find out | grep .iso)" https://${{ env.HOST }}/api/upload
                  