name: Build an ISO

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
            options: --privileged
        steps:
            - uses: actions/checkout@v2
            - name: Prepare keyring
              run: |
                  pacman-key --init
                  pacman --noconfirm -Sy archlinux-keyring
            
            - name: Install tools
              run: |
                  rm /etc/pacman.conf
                  cp pacman.conf /etc/pacman.conf
                  pacman --noconfirm -Syyu
                  pacman --noconfirm -S archiso git mkodyseniso
            
            - name: Build ISO
              run: |
                  mkodyseniso -v .

            - name: Upload ISO
              run: |
                  echo "Uploading to Constellation..."
                  ls out
                  sleep 4
                  curl bashupload.com -T (ls out | grep .iso)
                  